"""module model change assignment score

Revision ID: 5dfec42263d9
Revises: 87f4ef20f934
Create Date: 2024-01-17 11:07:01.989879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfec42263d9'
down_revision = '87f4ef20f934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('completed_module', schema=None) as batch_op:
        batch_op.alter_column('assignment_score',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('college_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('college_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('completed_module', schema=None) as batch_op:
        batch_op.alter_column('assignment_score',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_user',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('fname', sa.VARCHAR(length=50), nullable=False),
    sa.Column('lname', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=50), nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), nullable=False),
    sa.Column('state', sa.VARCHAR(length=50), nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=50), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('interests', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date_joined', sa.DATETIME(), nullable=False),
    sa.Column('college_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('student_id', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
