"""user module changes

Revision ID: 87f4ef20f934
Revises: ca56f31bfd4b
Create Date: 2024-01-16 23:06:06.521291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f4ef20f934'
down_revision = 'ca56f31bfd4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('college_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('college_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
